server:
  port: 9096
  servlet:
    context-path: /reward
spring:
  application:
    name: healthify-reward
  config:
    import: "optional:configserver:http://localhost:8888"
    label: default
  cloud:
    discovery:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true