server:
  port: 9092
  servlet:
    context-path: /notification
spring:
  application:
    name: healthify-notification
  config:
    import: "optional:configserver:http://localhost:8888"
    label: default
  cloud:
    discovery:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true