spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
        discovery.locator:
          enabled: true
          lowerCaseServiceId: true
        routes:
        - id: healthify-auth
          uri: lb://healthify-auth
          predicates:
          - Path=/auth/**
          filters:
          - PreserveHostHeader
        - id: doc-app
          uri: lb://doc-app
          predicates:
          - Path=/swagger/**
          filters:
          - RewritePath=/swagger/(?<path>.*), /$\{path}
        - id: healthify-challenge
          uri: lb://healthify-challenge
          predicates:
          - Path=/challenge/**
          filters:
          - PreserveHostHeader
        - id: healthify-reward
          uri: lb://healthify-reward
          predicates:
          - Path=/reward/**
          filters:
          - PreserveHostHeader
        - id: healthify-user
          uri: lb://healthify-user
          predicates:
          - Path=/user/**
          filters:
        - id: healthify-notification
          uri: lb://healthify-notification
          predicates:
          - Path=/notification/**
          filters:
          - PreserveHostHeader
