server:
  port: 9091
  servlet:
    context-path: /employee
spring:
  application:
    name: healthify-employee
  config:
    import: "optional:configserver:http://localhost:8888"
    label: default
  cloud:
    discovery:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
