server:
  port: 9084
  servlet:
    context-path: /challenge
spring:
  application:
    name: healthify-challenge
  config:
    import: "optional:configserver:http://localhost:8888"
    label: default
  cloud:
    discovery:
      enabled: true
