server:
  port: 8085
  servlet:
    context-path: /
spring:
  application:
    name: healthify-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
    label: default
  cloud:
    discovery:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true

---
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: healthify-auth
        url: /auth/v3/api-docs
      - name: healthify-challenge
        url: /challenge/v3/api-docs
      - name: healthify-reward
        url: /reward/v3/api-docs
      - name: healthify-employee
        url: /employee/v3/api-docs
      - name: healthify-notification
        url: /notification/v3/api-docs

jwt:
  secret: ${JWT_SECRET:R1BYcTVXVGNDU2JmWHVnZ1lnN0FKeGR3cU1RUU45QXV4SDJONFZ3ckhwS1N0ZjNCYVkzZ0F4RVBSS1UzRENwRw==}
  expirationms: ${JWT_EXPIRATIONMS:86400000}
